translate:
  sendq:
    id: aprsfeed.uplink1.num.sendq.bytes
    name: aprsfeed_sendq
    vertical_label: "bytes"
  age:
    id: aprsinject.worker1.aprs_stats.rate.age
    name: aprsinject_age
    vertical_label: "seconds"
  packet:
    id: aprsinject.worker1.aprs_stats.rate.packet
    name: aprsinject_packets
    vertical_label: "seconds"
  insert:
    id: store.time.sql.packet.insert
    name: aprsinject_insert
    vertical_label: "seconds"
